version: "3"
services:
  registry:
    image: registry:2.5.0
    environment: 
     - REGISTRY_HTTP_TLS_CERTIFICATE:/certs/domain.crt
     - REGISTRY_HTTP_TLS_KEY:/certs/domain.key
    ports:
      - "5000:5000"
    volumes:
      -  /home/josh/github/joshbrooks/docker-wharf/registry:/var/lib/registry 
      -  /home/josh/github/joshbrooks/docker-wharf/registry/certs:/certs
      -  /home/josh/apt-cacher-ng:/var/cache/apt-cacher-ng
