version: '2'
services:
  postgres:
    environment: 
        USER: mohinga
        DATABASE: mohinga_db
        RESTORE_FROM_DIRECTORY: /source
    image: timor-postgis
    restart: always
    ports:
    - "5434:5432"
    volumes:
    - /home/josh/Desktop/opgib/mohinga-production.catalpa.build/mohinga_db/0.0-110.20_1500290554:/source
